export default [
  {
    type: "The new S-class ",
    imageUri: require("./assets/newsclass1.jpg"),
    heading: "2021 S-Class",
    description:
      "the 2021 Mercedes-Benz S-class is the German company's flagship and a rolling statement of success. ",
    key: "1",
    color: "#9dcdfa",
  },
  {
    type: "exterior",
    imageUri: require("./assets/newsclass2.jpg"),
    heading: "Overview",
    description:
      "Although its storied history is partly responsible for that prestige, the latest generation looks to improve on its impressive predecessor in every way. ",
    key: "2",
    color: "#db9efa",
  },
  {
    type: "exterior",
    imageUri: require("./assets/newsclass3.jpg"),
    heading: "Great quality",
    description:
      "The new S-class has more impressive proportions, an even classier interior, and an impressive array of futuristic features. ",
    key: "3",
    color: "#999",
  },
  {
    type: "Rear Steer",
    imageUri: require("./assets/newsclass4.jpg"),
    heading: " all-wheel steering",
    description:
      "An optional four-wheel-steering system can turn the rear wheels as much as 10 degrees to reduce the turning circle.",
    key: "4",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: " interior ",
    imageUri: require("./assets/newsclass5.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "5",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "interior",
    imageUri: require("./assets/newsclass6.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "6",
    color: "#rgb(238, 146, 7)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass7.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "7",
    color: "#rgb(238, 146, 7)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass8.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "8",
    color: "#rgb(238, 146, 7)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass9.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "9",
    color: "#rgb(0, 38, 148)",
  },
  {
    type: "exterior",
    imageUri: require("./assets/newsclass10.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official exterior preview.",
    key: "10",
    color: "#rgb(122, 122, 122)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass11.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "11",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass12.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "12",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass13.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "13",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass14.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "14",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass15.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "15",
    color: "#rgb(171, 134, 1)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass16.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "16",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass17.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "17",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass18.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "18",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass19.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "19",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass20.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "20",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass21.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "21",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass22.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "22",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass23.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "23",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass24.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "24",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass25.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "25",
    color: "#rgb(0, 7, 27)",
  },
  {
    type: "INTERIOR",
    imageUri: require("./assets/newsclass26.jpg"),
    heading: "From Mercedes",
    description: "2021 Mercedes S-Class official interior preview.",
    key: "26",
    color: "#rgb(0, 66, 255)",
  },
];
